name: Tests

on:
  push:
    branches: [main, devel]
  pull_request:

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov toml
          pip install -e .

      - name: Run tests
        run: sh tests/run_tests_with_coverage.sh

      - name: Verify version sync
        run: |
          python -c "from runce import __version__; print(__version__)" > actual_version
          python -c "import toml; print(toml.load('pyproject.toml')['project'].get('version', 'DYNAMIC'))" > pyproject_version
          if [ $(cat pyproject_version) != "DYNAMIC" ] && [ $(cat pyproject_version) != $(cat actual_version) ]; then
            echo "Version mismatch!"
            exit 1
          fi

  Windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov toml
          pip install -e .

      - name: Run tests
        run: python -m pytest
